DROP TABLE IF EXISTS quota_events CASCADE;
DROP TABLE IF EXISTS llm_requests CASCADE;
DROP TABLE IF EXISTS usage_budgets CASCADE;
DROP TABLE IF EXISTS user_model_access CASCADE;
DROP TABLE IF EXISTS api_keys CASCADE;
DROP TABLE IF EXISTS provider_models CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS "QuotaEvent" CASCADE;
DROP TABLE IF EXISTS "LlmRequest" CASCADE;
DROP TABLE IF EXISTS "UsageBudget" CASCADE;
DROP TABLE IF EXISTS "UserModelAccess" CASCADE;
DROP TABLE IF EXISTS "ApiKey" CASCADE;
DROP TABLE IF EXISTS "ProviderModel" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;

DROP TABLE IF EXISTS "_prisma_migrations" CASCADE;

DROP TYPE IF EXISTS "RequestStatus" CASCADE;
DROP TYPE IF EXISTS "BudgetPeriod" CASCADE;
DROP TYPE IF EXISTS "ApiKeyStatus" CASCADE;
DROP TYPE IF EXISTS "UserStatus" CASCADE;
